### ISSUE TITLE
PDF Export raise expcetion TypeError: BrowserWindow is not a constructor

### ISSUE THREAD

**Issue by loic-fejoz** [loic-fejoz/dodoc#1]
Current [Dockerfile](https://github.com/loic-fejoz/dodoc/blob/dodoc2-dev-docker/Dockerfile) configuration raise an exception on PDF export:

```
/src/l-atelier-des-chercheurs/dodoc/core/exporter.js:250
              let win = new BrowserWindow({
                        ^

TypeError: BrowserWindow is not a constructor
    at fs.mkdirp (/src/l-atelier-des-chercheurs/dodoc/core/exporter.js:250:25)
    at xfs.mkdir.er (/src/l-atelier-des-chercheurs/dodoc/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by loic-fejoz** [comment]
According to @louis-ev I should have based my dev on [branch dodoc2-dev-node](https://github.com/l-atelier-des-chercheurs/dodoc/tree/dodoc2-dev-node).
Doing so I have a different error:

```
[14:34:26] - EXPORTER — makePDFForPubli : created cache folder at path /home/node/.cache/dodoc_cache/_publications
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome! spawn /src/l-atelier-des-chercheurs/dodoc/node_modules/puppeteer/.local-chromium/linux-672088/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by loic-fejoz** [comment]
digging https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-on-alpine

**Comment by loic-fejoz** [comment]
Close by 415dd501af1857e9fd001804d99cc211fb21d9da
